### ISSUE TITLE
How long will the board update?

### ISSUE THREAD

**Issue by zyznull** [microsoft/MSMARCO-Passage-Ranking-Submissions#14]
Hi, I have submitted a new result a week ago and successfully merged, but I notice that the result is not updated on the leadee board. So I want to know that how long will the board update? Thanks!

**Comment by bmitra-msft** [comment]
Hello,

Sincere apologies for the delay. The delay is due to pending automation of the leaderboard update. That was compounded by the fact that one of our team members who is working on the leaderboard migration had multiple deadlines last week and all of us have also been busy with the TREC Deep Learning Track. We will try to manually update the leaderboard soon. But in the meantime please feel free to use the evaluation results in your papers and presentations even if they are not on the official leaderboard yet.

We sincerely apologize for the inconvenience.

Best regards,
Bhaskar
